config/routes.rb
BballStats::Application.routes.draw do
  resources :stats_pitchers

  resources :stats_positions

  resources :players
  match 'team_players/:team_id', :to => 'players#team_view'
  match 'all_players/:year', :to => 'players#index'  

  resources :teams

  resources :divisions

  resources :leagues

  resources :seasons

  root :to => 'teams#index'

end

app/models/division.rb
class Division < ActiveRecord::Base
  belongs_to :league
  belongs_to :season
  attr_accessible :division_name
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @divisions }
    end
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
    @division = Division.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/new
  # GET /divisions/new.json
  def new
    @division = Division.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/1/edit
  def edit
    @division = Division.find(params[:id])
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(params[:division])

    respond_to do |format|
      if @division.save
        format.html { redirect_to @division, notice: 'Division was successfully created.' }
        format.json { render json: @division, status: :created, location: @division }
      else
        format.html { render action: "new" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /divisions/1
  # PUT /divisions/1.json
  def update
    @division = Division.find(params[:id])

    respond_to do |format|
      if @division.update_attributes(params[:division])
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division = Division.find(params[:id])
    @division.destroy

    respond_to do |format|
      format.html { redirect_to divisions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= form_for(@division) do |f| %>
  <% if @division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% @division.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :league %><br />
    <%= f.text_field :league %>
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :division_name %><br />
    <%= f.text_field :division_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render 'form' %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<h1>Listing divisions</h1>

<table>
  <tr>
    <th>League</th>
    <th>Season</th>
    <th>Division name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @divisions.each do |division| %>
  <tr>
    <td><%= division.league %></td>
    <td><%= division.season %></td>
    <td><%= division.division_name %></td>
    <td><%= link_to 'Show', division %></td>
    <td><%= link_to 'Edit', edit_division_path(division) %></td>
    <td><%= link_to 'Destroy', division, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Division', new_division_path %>

app/views/divisions/new.html.erb
<h1>New division</h1>

<%= render 'form' %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>League:</b>
  <%= @division.league %>
</p>

<p>
  <b>Season:</b>
  <%= @division.season %>
</p>

<p>
  <b>Division name:</b>
  <%= @division.division_name %>
</p>


<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>