config/routes.rb
BballStats::Application.routes.draw do
  resources :stats_pitchers

  resources :stats_positions

  resources :players
  match 'team_players/:team_id', :to => 'players#team_view'
  match 'all_players/:year', :to => 'players#index'  

  resources :teams

  resources :divisions

  resources :leagues

  resources :seasons

  root :to => 'teams#index'

end

app/models/stats_pitcher.rb
class StatsPitcher < ActiveRecord::Base
  belongs_to :player
  belongs_to :team
  belongs_to :season
  attr_accessible :balk, :complete_games, :earned_runs, :era, :games, :games_started, :hit_batter, :home_runs, :innings, :losses, :runs, :saves, :shut_outs, :struck_out_batter, :walked_batter, :wild_pitches, :wins, :player_id
end

app/controllers/stats_pitchers_controller.rb
class StatsPitchersController < ApplicationController
  # GET /stats_pitchers
  # GET /stats_pitchers.json
  def index
    @stats_pitchers = StatsPitcher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stats_pitchers }
    end
  end

  # GET /stats_pitchers/1
  # GET /stats_pitchers/1.json
  def show
    @stats_pitcher = StatsPitcher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stats_pitcher }
    end
  end

  # GET /stats_pitchers/new
  # GET /stats_pitchers/new.json
  def new
    @stats_pitcher = StatsPitcher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stats_pitcher }
    end
  end

  # GET /stats_pitchers/1/edit
  def edit
    @stats_pitcher = StatsPitcher.find(params[:id])
  end

  # POST /stats_pitchers
  # POST /stats_pitchers.json
  def create
    @stats_pitcher = StatsPitcher.new(params[:stats_pitcher])

    respond_to do |format|
      if @stats_pitcher.save
        format.html { redirect_to @stats_pitcher, notice: 'Stats pitcher was successfully created.' }
        format.json { render json: @stats_pitcher, status: :created, location: @stats_pitcher }
      else
        format.html { render action: "new" }
        format.json { render json: @stats_pitcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stats_pitchers/1
  # PUT /stats_pitchers/1.json
  def update
    @stats_pitcher = StatsPitcher.find(params[:id])

    respond_to do |format|
      if @stats_pitcher.update_attributes(params[:stats_pitcher])
        format.html { redirect_to @stats_pitcher, notice: 'Stats pitcher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stats_pitcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats_pitchers/1
  # DELETE /stats_pitchers/1.json
  def destroy
    @stats_pitcher = StatsPitcher.find(params[:id])
    @stats_pitcher.destroy

    respond_to do |format|
      format.html { redirect_to stats_pitchers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stats_pitchers_helper.rb
module StatsPitchersHelper
end

app/views/stats_pitchers/_form.html.erb
<%= form_for(@stats_pitcher) do |f| %>
  <% if @stats_pitcher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stats_pitcher.errors.count, "error") %> prohibited this stats_pitcher from being saved:</h2>

      <ul>
      <% @stats_pitcher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player %><br />
    <%= f.text_field :player %>
  </div>
  <div class="field">
    <%= f.label :team %><br />
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :wins %><br />
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :losses %><br />
    <%= f.number_field :losses %>
  </div>
  <div class="field">
    <%= f.label :saves %><br />
    <%= f.number_field :saves %>
  </div>
  <div class="field">
    <%= f.label :games %><br />
    <%= f.number_field :games %>
  </div>
  <div class="field">
    <%= f.label :games_started %><br />
    <%= f.number_field :games_started %>
  </div>
  <div class="field">
    <%= f.label :complete_games %><br />
    <%= f.number_field :complete_games %>
  </div>
  <div class="field">
    <%= f.label :shut_outs %><br />
    <%= f.number_field :shut_outs %>
  </div>
  <div class="field">
    <%= f.label :era %><br />
    <%= f.text_field :era %>
  </div>
  <div class="field">
    <%= f.label :innings %><br />
    <%= f.number_field :innings %>
  </div>
  <div class="field">
    <%= f.label :home_runs %><br />
    <%= f.number_field :home_runs %>
  </div>
  <div class="field">
    <%= f.label :runs %><br />
    <%= f.number_field :runs %>
  </div>
  <div class="field">
    <%= f.label :earned_runs %><br />
    <%= f.number_field :earned_runs %>
  </div>
  <div class="field">
    <%= f.label :hit_batter %><br />
    <%= f.number_field :hit_batter %>
  </div>
  <div class="field">
    <%= f.label :wild_pitches %><br />
    <%= f.number_field :wild_pitches %>
  </div>
  <div class="field">
    <%= f.label :balk %><br />
    <%= f.number_field :balk %>
  </div>
  <div class="field">
    <%= f.label :walked_batter %><br />
    <%= f.number_field :walked_batter %>
  </div>
  <div class="field">
    <%= f.label :struck_out_batter %><br />
    <%= f.number_field :struck_out_batter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stats_pitchers/edit.html.erb
<h1>Editing stats_pitcher</h1>

<%= render 'form' %>

<%= link_to 'Show', @stats_pitcher %> |
<%= link_to 'Back', stats_pitchers_path %>

app/views/stats_pitchers/index.html.erb
<h1>Listing stats_pitchers</h1>

<table>
  <tr>
    <th>Player</th>
    <th>Team</th>
    <th>Season</th>
    <th>Wins</th>
    <th>Losses</th>
    <th>Saves</th>
    <th>Games</th>
    <th>Games started</th>
    <th>Complete games</th>
    <th>Shut outs</th>
    <th>Era</th>
    <th>Innings</th>
    <th>Home runs</th>
    <th>Runs</th>
    <th>Earned runs</th>
    <th>Hit batter</th>
    <th>Wild pitches</th>
    <th>Balk</th>
    <th>Walked batter</th>
    <th>Struck out batter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stats_pitchers.each do |stats_pitcher| %>
  <tr>
    <td><%= stats_pitcher.player %></td>
    <td><%= stats_pitcher.team %></td>
    <td><%= stats_pitcher.season %></td>
    <td><%= stats_pitcher.wins %></td>
    <td><%= stats_pitcher.losses %></td>
    <td><%= stats_pitcher.saves %></td>
    <td><%= stats_pitcher.games %></td>
    <td><%= stats_pitcher.games_started %></td>
    <td><%= stats_pitcher.complete_games %></td>
    <td><%= stats_pitcher.shut_outs %></td>
    <td><%= stats_pitcher.era %></td>
    <td><%= stats_pitcher.innings %></td>
    <td><%= stats_pitcher.home_runs %></td>
    <td><%= stats_pitcher.runs %></td>
    <td><%= stats_pitcher.earned_runs %></td>
    <td><%= stats_pitcher.hit_batter %></td>
    <td><%= stats_pitcher.wild_pitches %></td>
    <td><%= stats_pitcher.balk %></td>
    <td><%= stats_pitcher.walked_batter %></td>
    <td><%= stats_pitcher.struck_out_batter %></td>
    <td><%= link_to 'Show', stats_pitcher %></td>
    <td><%= link_to 'Edit', edit_stats_pitcher_path(stats_pitcher) %></td>
    <td><%= link_to 'Destroy', stats_pitcher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stats pitcher', new_stats_pitcher_path %>

app/views/stats_pitchers/new.html.erb
<h1>New stats_pitcher</h1>

<%= render 'form' %>

<%= link_to 'Back', stats_pitchers_path %>

app/views/stats_pitchers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Player:</b>
  <%= @stats_pitcher.player %>
</p>

<p>
  <b>Team:</b>
  <%= @stats_pitcher.team %>
</p>

<p>
  <b>Season:</b>
  <%= @stats_pitcher.season %>
</p>

<p>
  <b>Wins:</b>
  <%= @stats_pitcher.wins %>
</p>

<p>
  <b>Losses:</b>
  <%= @stats_pitcher.losses %>
</p>

<p>
  <b>Saves:</b>
  <%= @stats_pitcher.saves %>
</p>

<p>
  <b>Games:</b>
  <%= @stats_pitcher.games %>
</p>

<p>
  <b>Games started:</b>
  <%= @stats_pitcher.games_started %>
</p>

<p>
  <b>Complete games:</b>
  <%= @stats_pitcher.complete_games %>
</p>

<p>
  <b>Shut outs:</b>
  <%= @stats_pitcher.shut_outs %>
</p>

<p>
  <b>Era:</b>
  <%= @stats_pitcher.era %>
</p>

<p>
  <b>Innings:</b>
  <%= @stats_pitcher.innings %>
</p>

<p>
  <b>Home runs:</b>
  <%= @stats_pitcher.home_runs %>
</p>

<p>
  <b>Runs:</b>
  <%= @stats_pitcher.runs %>
</p>

<p>
  <b>Earned runs:</b>
  <%= @stats_pitcher.earned_runs %>
</p>

<p>
  <b>Hit batter:</b>
  <%= @stats_pitcher.hit_batter %>
</p>

<p>
  <b>Wild pitches:</b>
  <%= @stats_pitcher.wild_pitches %>
</p>

<p>
  <b>Balk:</b>
  <%= @stats_pitcher.balk %>
</p>

<p>
  <b>Walked batter:</b>
  <%= @stats_pitcher.walked_batter %>
</p>

<p>
  <b>Struck out batter:</b>
  <%= @stats_pitcher.struck_out_batter %>
</p>


<%= link_to 'Edit', edit_stats_pitcher_path(@stats_pitcher) %> |
<%= link_to 'Back', stats_pitchers_path %>