config/routes.rb
BballStats::Application.routes.draw do
  resources :stats_pitchers

  resources :stats_positions

  resources :players
  match 'team_players/:team_id', :to => 'players#team_view'
  match 'all_players/:year', :to => 'players#index'  

  resources :teams

  resources :divisions

  resources :leagues

  resources :seasons

  root :to => 'teams#index'

end

app/models/stats_position.rb
## GG, TECH_DEBT - depending on future intended features, this could be pulled into StatsPosition class.  Just depends on client side data being displayed.  Right now, these are the only attributes for the demo
class StatsHitter
  attr_accessor :player_id, :avg, :hr, :rbi, :runs, :sb, :ops
end

class StatsPosition < ActiveRecord::Base
  belongs_to :player
  belongs_to :team
  belongs_to :season
  ## GG, added player_id at end explicitly b/c of mass asignment error / security
  attr_accessible :at_bats, :caught_stealing, :doubles, :fielding_errors, :games, :games_started, :hit_by_pitch, :hits, :home_runs, :pb, :rbi, :runs, :sacrifice_flies, :sacrifice_hits, :steals, :struck_out, :triples, :walks, :player_id

  ## 
  ## read DB for this player stats, calculate
  def self.get_stats_hitter(player_id)
    sh = StatsHitter.new
    
    sp = StatsPosition.find_by_player_id(player_id)
    return nil if sp.nil?
    #puts sp.inspect

    sh.player_id = sp.player_id

    #AVG, HR, RBI, RUNS, SB, and OPS
    sh.hr   = sp.home_runs
    sh.rbi  = sp.rbi
    sh.runs = sp.runs
    sh.sb   = sp.steals

    # AVG
    # avg = H /AB
    if sp.at_bats.to_f == 0
      sh.avg = 0.0
    else
      sh.avg = sp.hits.to_f / sp.at_bats.to_f
    end

    # OPS
    # ops = AB * (H + BB + HBP) + TB * (AB + BB + SF + HBP) / AB * (AB + BB + SF + HBP)
    # TB = 1B + 2(2B) + 3(3B) + 4(HR)
    singles = sp.hits - sp.home_runs - sp.doubles - sp.triples
    total_bases = singles + 2*(sp.doubles) + 3*(sp.triples) + 4*(sp.home_runs)
    if (sp.at_bats * ( sp.at_bats + sp.walks + sp.sacrifice_flies + sp.hit_by_pitch)) == 0
      sh.ops = 0.0
    else
      sh.ops = (sp.at_bats * ( sp.hits + sp.walks + sp.hit_by_pitch) + 
                total_bases * (sp.at_bats + sp.walks + sp.sacrifice_flies + sp.hit_by_pitch)).to_f / 
        (sp.at_bats * ( sp.at_bats + sp.walks + sp.sacrifice_flies + sp.hit_by_pitch)).to_f
    end

    sh
  end
  
end

app/controllers/stats_positions_controller.rb
class StatsPositionsController < ApplicationController
  # GET /stats_positions
  # GET /stats_positions.json
  def index
    @stats_positions = StatsPosition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stats_positions }
    end
  end

  # GET /stats_positions/1
  # GET /stats_positions/1.json
  def show
    @stats_position = StatsPosition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stats_position }
    end
  end

  # GET /stats_positions/new
  # GET /stats_positions/new.json
  def new
    @stats_position = StatsPosition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stats_position }
    end
  end

  # GET /stats_positions/1/edit
  def edit
    @stats_position = StatsPosition.find(params[:id])
  end

  # POST /stats_positions
  # POST /stats_positions.json
  def create
    @stats_position = StatsPosition.new(params[:stats_position])

    respond_to do |format|
      if @stats_position.save
        format.html { redirect_to @stats_position, notice: 'Stats position was successfully created.' }
        format.json { render json: @stats_position, status: :created, location: @stats_position }
      else
        format.html { render action: "new" }
        format.json { render json: @stats_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stats_positions/1
  # PUT /stats_positions/1.json
  def update
    @stats_position = StatsPosition.find(params[:id])

    respond_to do |format|
      if @stats_position.update_attributes(params[:stats_position])
        format.html { redirect_to @stats_position, notice: 'Stats position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stats_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats_positions/1
  # DELETE /stats_positions/1.json
  def destroy
    @stats_position = StatsPosition.find(params[:id])
    @stats_position.destroy

    respond_to do |format|
      format.html { redirect_to stats_positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stats_positions_helper.rb
module StatsPositionsHelper
end

app/views/stats_positions/_form.html.erb
<%= form_for(@stats_position) do |f| %>
  <% if @stats_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stats_position.errors.count, "error") %> prohibited this stats_position from being saved:</h2>

      <ul>
      <% @stats_position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player %><br />
    <%= f.text_field :player %>
  </div>
  <div class="field">
    <%= f.label :team %><br />
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :games %><br />
    <%= f.number_field :games %>
  </div>
  <div class="field">
    <%= f.label :games_started %><br />
    <%= f.number_field :games_started %>
  </div>
  <div class="field">
    <%= f.label :at_bats %><br />
    <%= f.number_field :at_bats %>
  </div>
  <div class="field">
    <%= f.label :runs %><br />
    <%= f.number_field :runs %>
  </div>
  <div class="field">
    <%= f.label :hits %><br />
    <%= f.number_field :hits %>
  </div>
  <div class="field">
    <%= f.label :doubles %><br />
    <%= f.number_field :doubles %>
  </div>
  <div class="field">
    <%= f.label :triples %><br />
    <%= f.number_field :triples %>
  </div>
  <div class="field">
    <%= f.label :home_runs %><br />
    <%= f.number_field :home_runs %>
  </div>
  <div class="field">
    <%= f.label :rbi %><br />
    <%= f.number_field :rbi %>
  </div>
  <div class="field">
    <%= f.label :steals %><br />
    <%= f.number_field :steals %>
  </div>
  <div class="field">
    <%= f.label :caught_stealing %><br />
    <%= f.number_field :caught_stealing %>
  </div>
  <div class="field">
    <%= f.label :sacrifice_hits %><br />
    <%= f.number_field :sacrifice_hits %>
  </div>
  <div class="field">
    <%= f.label :sacrifice_flies %><br />
    <%= f.number_field :sacrifice_flies %>
  </div>
  <div class="field">
    <%= f.label :fielding_errors %><br />
    <%= f.number_field :fielding_errors %>
  </div>
  <div class="field">
    <%= f.label :pb %><br />
    <%= f.number_field :pb %>
  </div>
  <div class="field">
    <%= f.label :walks %><br />
    <%= f.number_field :walks %>
  </div>
  <div class="field">
    <%= f.label :struck_out %><br />
    <%= f.number_field :struck_out %>
  </div>
  <div class="field">
    <%= f.label :hit_by_pitch %><br />
    <%= f.number_field :hit_by_pitch %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stats_positions/edit.html.erb
<h1>Editing stats_position</h1>

<%= render 'form' %>

<%= link_to 'Show', @stats_position %> |
<%= link_to 'Back', stats_positions_path %>

app/views/stats_positions/index.html.erb
<h1>Listing stats_positions</h1>

<table>
  <tr>
    <th>Player</th>
    <th>Team</th>
    <th>Season</th>
    <th>Games</th>
    <th>Games started</th>
    <th>At bats</th>
    <th>Runs</th>
    <th>Hits</th>
    <th>Doubles</th>
    <th>Triples</th>
    <th>Home runs</th>
    <th>Rbi</th>
    <th>Steals</th>
    <th>Caught stealing</th>
    <th>Sacrifice hits</th>
    <th>Sacrifice flies</th>
    <th>Errors</th>
    <th>Pb</th>
    <th>Walks</th>
    <th>Struck out</th>
    <th>Hit by pitch</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stats_positions.each do |stats_position| %>
  <tr>
    <td><%= stats_position.player %></td>
    <td><%= stats_position.team %></td>
    <td><%= stats_position.season %></td>
    <td><%= stats_position.games %></td>
    <td><%= stats_position.games_started %></td>
    <td><%= stats_position.at_bats %></td>
    <td><%= stats_position.runs %></td>
    <td><%= stats_position.hits %></td>
    <td><%= stats_position.doubles %></td>
    <td><%= stats_position.triples %></td>
    <td><%= stats_position.home_runs %></td>
    <td><%= stats_position.rbi %></td>
    <td><%= stats_position.steals %></td>
    <td><%= stats_position.caught_stealing %></td>
    <td><%= stats_position.sacrifice_hits %></td>
    <td><%= stats_position.sacrifice_flies %></td>
    <td><%= stats_position.errors %></td>
    <td><%= stats_position.pb %></td>
    <td><%= stats_position.walks %></td>
    <td><%= stats_position.struck_out %></td>
    <td><%= stats_position.hit_by_pitch %></td>
    <td><%= link_to 'Show', stats_position %></td>
    <td><%= link_to 'Edit', edit_stats_position_path(stats_position) %></td>
    <td><%= link_to 'Destroy', stats_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stats position', new_stats_position_path %>

app/views/stats_positions/new.html.erb
<h1>New stats_position</h1>

<%= render 'form' %>

<%= link_to 'Back', stats_positions_path %>

app/views/stats_positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Player:</b>
  <%= @stats_position.player %>
</p>

<p>
  <b>Team:</b>
  <%= @stats_position.team %>
</p>

<p>
  <b>Season:</b>
  <%= @stats_position.season %>
</p>

<p>
  <b>Games:</b>
  <%= @stats_position.games %>
</p>

<p>
  <b>Games started:</b>
  <%= @stats_position.games_started %>
</p>

<p>
  <b>At bats:</b>
  <%= @stats_position.at_bats %>
</p>

<p>
  <b>Runs:</b>
  <%= @stats_position.runs %>
</p>

<p>
  <b>Hits:</b>
  <%= @stats_position.hits %>
</p>

<p>
  <b>Doubles:</b>
  <%= @stats_position.doubles %>
</p>

<p>
  <b>Triples:</b>
  <%= @stats_position.triples %>
</p>

<p>
  <b>Home runs:</b>
  <%= @stats_position.home_runs %>
</p>

<p>
  <b>Rbi:</b>
  <%= @stats_position.rbi %>
</p>

<p>
  <b>Steals:</b>
  <%= @stats_position.steals %>
</p>

<p>
  <b>Caught stealing:</b>
  <%= @stats_position.caught_stealing %>
</p>

<p>
  <b>Sacrifice hits:</b>
  <%= @stats_position.sacrifice_hits %>
</p>

<p>
  <b>Sacrifice flies:</b>
  <%= @stats_position.sacrifice_flies %>
</p>

<p>
  <b>Fielding Errors:</b>
  <%= @stats_position.fielding_errors %>
</p>

<p>
  <b>Pb:</b>
  <%= @stats_position.pb %>
</p>

<p>
  <b>Walks:</b>
  <%= @stats_position.walks %>
</p>

<p>
  <b>Struck out:</b>
  <%= @stats_position.struck_out %>
</p>

<p>
  <b>Hit by pitch:</b>
  <%= @stats_position.hit_by_pitch %>
</p>


<%= link_to 'Edit', edit_stats_position_path(@stats_position) %> |
<%= link_to 'Back', stats_positions_path %>